import * as Yup from "yup";

export const BrokenValues = {
  rkmDof3a: "",
  tary5eda3: "",
  tary5f2s: "",
  rkm3ayna: "",
  mazr3a: "",
  Anbar: "",
  age: "",
  AynaNum: "",
  EggCount: "",
  INFERTILE: "",
  EARLY: "",
  BLOOD_RING: "",
  BLACK_EYE: "",
  Ten_DAYS: "",
  FEATHER: "",
  LATE_LIFE: "",
  LATE_DEAD: "",
  PIP_LIFE: "",
  PIP_DEAD: "",
  SHELLQUALITY: "",
  ROTTEN: "",
  CONTAMINATION: "",
  M_POSETION: "",
  M_FORMATION: "",
  CULLS: "",
  DEAD_CHICKS: "",
};

export const Validation = Yup.object({
  rkmDof3a: Yup.number().required("يجب ادخال رقم الدفعه"),
  tary5eda3: Yup.date().required("ادخل تاريخ الاداع"),
  tary5f2s: Yup.date().required("ادخل تاريخ الفقص"),
  rkm3ayna: Yup.number().required("يجب ادخال رقم العينه"),
  mazr3a: Yup.string().required("يجب ادخال المزرعه"),
  Anbar: Yup.number().required("يجب ادخل هذا العنصر"),
  age: Yup.number().required("يجب ادخل هذا العنصر"),
  AynaNum: Yup.number().required("يجب ادخل هذا العنصر"),
  EggCount: Yup.number().required("يجب ادخل هذا العنصر"),
  INFERTILE: Yup.number().required("يجب ادخل هذا العنصر"),
  EARLY: Yup.number().required("يجب ادخل هذا العنصر"),

  BLOOD_RING: Yup.number().required("يجب ادخل هذا العنصر"),
  BLACK_EYE: Yup.number().required("يجب ادخل هذا العنصر"),
  Ten_DAYS: Yup.number().required("يجب ادخل هذا العنصر"),
  FEATHER: Yup.number().required("يجب ادخل هذا العنصر"),
  LATE_LIFE: Yup.number().required("يجب ادخل هذا العنصر"),
  LATE_DEAD: Yup.number().required("يجب ادخل هذا العنصر"),
  PIP_LIFE: Yup.number().required("يجب ادخل هذا العنصر"),
  PIP_DEAD: Yup.number().required("يجب ادخل هذا العنصر"),
  SHELLQUALITY: Yup.number().required("يجب ادخل هذا العنصر"),
  ROTTEN: Yup.number().required("يجب ادخل هذا العنصر"),
  CONTAMINATION: Yup.number().required("يجب ادخل هذا العنصر"),
  M_POSETION: Yup.number().required("يجب ادخل هذا العنصر"),
  M_FORMATION: Yup.number().required("يجب ادخل هذا العنصر"),
  CULLS: Yup.number().required("يجب ادخل هذا العنصر"),
  DEAD_CHICKS: Yup.number().required("يجب ادخل هذا العنصر"),
});
